build:
	gcc -g -Wall -Wextra -std=c99 question1.c -o question1.o
	gcc -g -Wall -Wextra -std=c99 question2.c -o question2.o
	gcc -g -Wall -Wextra -std=gnu99 sigtrap.c -o process
	gcc -g -Wall -Wextra -std=c99 question3.c -o question3.o
	gcc -g -Wall -Wextra -std=c99 question4.c -o question4.o
	gcc -g -Wall -Wextra -std=c99 question5.c -o question5.o
