build:
	gcc-7 -Wall -Wextra -std=c99 -fopenmp demo_1.c -o demo_1.o -lm
	gcc-7 -Wall -Wextra -std=c99 -fopenmp demo_2.c -o demo_2.o -lm
	gcc-7 -Wall -Wextra -std=c99 -fopenmp demo_3.c -o demo_3.o -lm
	gcc-7 -Wall -Wextra -std=c99 -fopenmp demo_4.c -o demo_4.o -lm
	gcc-7 -g -Wall -Wextra -std=c99 -fopenmp question2.c -o question2.o -lm
	gcc-7 -g -Wall -Wextra -std=c99 -fopenmp question3.c -o question3.o -lm
	gcc-7 -g -Wall -Wextra -std=c99 -fopenmp question4.c -o question4.o -lm
	gcc-7 -g -Wall -Wextra -std=c99 -fopenmp question5.c -o question5.o -lm
